### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Julien-Broyard/socketio-chat#1]
Hello @Julien-Broyard  Here/s what I came up with this other project of yours..I hope you like it! If you do, then I will male a PR for the files next..

![PRES-01-01-01](https://user-images.githubusercontent.com/36028424/55739794-59b47300-5a5c-11e9-9496-a4b27d6047ed.png)

**Comment by Julien-Broyard** [comment]
Nice simple and clean, just awesome :+1:

**Comment by Tobaloidee** [comment]
So glad that you again liked it! will prepare the files and make a PR with it.. :)

**Comment by Tobaloidee** [comment]
which color do you prefer from the 3 versions? even though I will make all of it

**Comment by Tobaloidee** [comment]
Surely! 💯

**Comment by Tobaloidee** [comment]
Here's the PR #2 @Julien-Broyard  👍 and you can download all the files, versions & formats on this [LINK](https://drive.google.com/drive/u/1/folders/13vbsD58nEEblXgzrsoJ_BSBWgYD36H8k) to my drive! All yours! 💯  Thanks so much!

**Comment by Julien-Broyard** [comment]
Thank you so much !

**Comment by Tobaloidee** [comment]
next is Agence-Voyage? maybe tomorrow if you let me.. :)

**Comment by Julien-Broyard** [comment]
Wow you're on fire :fire: :fire_engine:

**Comment by Tobaloidee** [comment]
I want to work more coz I have been away from a while last year.. 👍  What does Agence-Voyage do?

**Comment by Julien-Broyard** [comment]
It's an landing page made for a travel agency that I've created (And don't worry when I'll have time I'll translate the french in english and I'll upload the website on netlify :smile:

**Comment by Tobaloidee** [comment]
Awesome projects you got..will work on it tomorrow! See you then @Julien-Broyard  Thanks again for allowing and accepting my contributions! 🥇

**Comment by Julien-Broyard** [comment]
Thans you for your work as well !

**Comment by Tobaloidee** [comment]
Hi @Julien-Broyard  I made changes in the readme as i've noticed a dent on the logotype
here's the new PR #3
